name: auto_validate
description: Auto Validate Package
version: 1.0.0
author: Mahmoud El Shenawy
homepage: https://github.com/Mahmoud-ElShenawy/auto_validate

#  Created By Mahmoud El Shenawy (Dev.Mahmoud.ElShenawy@Gmail.com)


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  freezed:
  build_runner:


